// <auto-generated/>
#pragma warning disable CS0618
using LupiraCalBff.Upstream.Contact.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LupiraCalBff.Upstream.Contact.Sync.Containers
{
    /// <summary>
    /// Builds and executes requests for operations under \sync\containers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContainersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Sync.Containers.ContainersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sync/containers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Sync.Containers.ContainersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sync/containers", rawUrl)
        {
        }
        /// <summary>
        /// Snapshot of the caller&apos;s address books + contact groups for mirror reconciliation (no cursor — fetch once per sync cycle and diff locally).
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse>(requestInfo, global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Snapshot of the caller&apos;s address books + contact groups for mirror reconciliation (no cursor — fetch once per sync cycle and diff locally).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Sync.Containers.ContainersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LupiraCalBff.Upstream.Contact.Sync.Containers.ContainersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LupiraCalBff.Upstream.Contact.Sync.Containers.ContainersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContainersRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
