// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace LupiraCalBff.Upstream.Contact.Models
{
    /// <summary>A principal&apos;s permission on a collection. `Owner` adds member-management + delete rights over `ReadWrite`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Access
    {
        [EnumMember(Value = "Owner")]
        #pragma warning disable CS1591
        Owner,
        #pragma warning restore CS1591
        [EnumMember(Value = "ReadWrite")]
        #pragma warning disable CS1591
        ReadWrite,
        #pragma warning restore CS1591
        [EnumMember(Value = "Read")]
        #pragma warning disable CS1591
        Read,
        #pragma warning restore CS1591
    }
}
