// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LupiraCalBff.Upstream.Contact.Models
{
    /// <summary>
    /// Snapshot of the caller&apos;s containers. Address books are plain documents (no cursor); groups are            event-sourced but small and fully replaced each cycle — both are fetched once per sync cycle and diffed            against the mirror.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SyncContainersResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addressBooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LupiraCalBff.Upstream.Contact.Models.AddressBookDto>? AddressBooks { get; set; }
#nullable restore
#else
        public List<global::LupiraCalBff.Upstream.Contact.Models.AddressBookDto> AddressBooks { get; set; }
#endif
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto>? Groups { get; set; }
#nullable restore
#else
        public List<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto> Groups { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse"/> and sets the default values.
        /// </summary>
        public SyncContainersResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LupiraCalBff.Upstream.Contact.Models.SyncContainersResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addressBooks", n => { AddressBooks = n.GetCollectionOfObjectValues<global::LupiraCalBff.Upstream.Contact.Models.AddressBookDto>(global::LupiraCalBff.Upstream.Contact.Models.AddressBookDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "groups", n => { Groups = n.GetCollectionOfObjectValues<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto>(global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::LupiraCalBff.Upstream.Contact.Models.AddressBookDto>("addressBooks", AddressBooks);
            writer.WriteCollectionOfObjectValues<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto>("groups", Groups);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
